services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_PORT=5678
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Europe/Kiev
      - TZ=Europe/Kiev
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n-files:/files

volumes:
  n8n_data:
